### ISSUE TITLE
No matching function call

### ISSUE THREAD

**Issue by the4thamigo-uk** [pgspider/parquet_s3_fdw#19]
Hi, I really want to use this on a project. I think it would be useful, but currently it's kinda let down by some incomplete build instructions. Ive managed to get through quite a few hurdles here bu I am struggling now with : 

```
arquet_s3_fdw_connection.cpp:518:69: error: no matching function for call to ‘Aws::S3::S3Client::S3Client(Aws::Auth::AWSCredentials&, Aws::Client::ClientConfiguration&)’
  518 |                 s3_client = new Aws::S3::S3Client(cred, clientConfig);

```

An example build in a Dockerfile would really help I think.

**Comment by hrkuma** [comment]
Hi,
It seems in latest AWS ASK CPP this error occurrs.
At least, I could build using version of refs/tags/1.9.312.
(In my environment postgres and aws-sdk-cpp is built from source code, so maybe we have more differences.)
